print ("Rissha Angeline Jalotjot")
print ("Catubugan, Boac, Marinduque")
print ("July 4, 2001")
print ("Marinduque State College")
print ("Bachelor of Science in Information Technology")
print ("2nd year - Section A")